# Site settings
title: Refollow
email: support@refollow.com
description: "Here you will find helpful documentation, video walkthroughs, and beneficial articles about how to improve social media marketing"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 40C79D
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Originate
  location: Location
  social: Follow us

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/refollow
  - title: facebook
    url: http://facebook.com/Refollow

# Postal address (add as many lines as necessary)
address:
  - line: 580 Market St
  - line: San Francisco, CA 94104

# Build settings
markdown: kramdown
permalink: pretty
